"""Updete

Revision ID: 27ecaed4ba9e
Revises: b00ea97f03a4
Create Date: 2025-10-08 14:10:31.991050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ecaed4ba9e'
down_revision: Union[str, Sequence[str], None] = 'b00ea97f03a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_technologles_name'), 'technologles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technologles_name'), table_name='technologles')
    # ### end Alembic commands ###
